### ISSUE TITLE
Bug: Roundtrip Tests for RestClient does not work

### ISSUE THREAD

**Issue by Du-z** [ProphetLamb/Surreal.Net#18]
Currently the most of the RPC Round Trip tests work, However the Rest Round Trips do not.

Looks like this mostly has to do with the document result not being returned like they are with RPC.

**Comment by ProphetLamb** [comment]
I debugged each of the tests and it would appear that they **could** not ever work, becasue the REST interface of SurrealDB is buggy. For instance `Query` 
```sql
SELECT * FROM object:123
```
returns the document with the id `object:123` on RPC, but an empty document for REST. Ive validated this using a REST client.

Now if we query
```sql
SELECT * FROM object
```
we are returned a list of all documents in `object` including `123`.

**Comment by ProphetLamb** [comment]
With this in mind i feel confident to merge #26 and release v1 with a disclaimer on`DbRest`.

Thanks a lot for your great work, and taking the time to write the roundtrip tests <3
