### ISSUE TITLE
Feature: Query Parameters must be 'stringified' for them to work

### ISSUE THREAD

**Issue by Du-z** [ProphetLamb/Surreal.Net#19]
See the test `RpcRoundTripTests.CreateAndParameterizedQueryRoundTripTest` for an example where a struct must be converted to a to work.

https://github.com/ProphetLamb/Surreal.Net/blob/3ed84b191f60a98dd82837beec744d3e71129ae6/tests/Core.Tests/RoundTripTests.cs#L93

**Comment by ProphetLamb** [comment]
Fixed in #26

**Comment by Du-z** [comment]
Yeah looks good!
