### ISSUE TITLE
Bug: Floating point numbers are not inserted into the database correctly

### ISSUE THREAD

**Issue by Du-z** [ProphetLamb/Surreal.Net#24]
Floating point numbers do not survive a roundtrip.

They seem to be inserted as a string with many trailer zeros.
`"PositiveFloat": "48611764000000000000000000000000000000"`

Uncomment the following line and run the test `RpcRoundTripTests.CreateRoundTripTest`

https://github.com/ProphetLamb/Surreal.Net/blob/3ed84b191f60a98dd82837beec744d3e71129ae6/tests/Core.Tests/RoundTripTests.cs#L137

When uncommenting these properties skip the ones that are marked as "Not Supported by System.Text.Json".

**Comment by ProphetLamb** [comment]
I opened #26 for those issues. The float serialization is fixed

**Comment by ProphetLamb** [comment]
Fixed with #26
