### ISSUE TITLE
Bug: DateTimes are not inserted into the database correctly

### ISSUE THREAD

**Issue by Du-z** [ProphetLamb/Surreal.Net#25]
DateTimes do not survive a roundtrip.

They seem to be inserted with two zeros prepended to the fractions part of the time.
`"MaxUtcDateTime": "9999-12-31T23:59:59.009999999Z"`

Uncomment the following line and run the test `RpcRoundTripTests.CreateRoundTripTest`

https://github.com/ProphetLamb/Surreal.Net/blob/3ed84b191f60a98dd82837beec744d3e71129ae6/tests/Core.Tests/RoundTripTests.cs#L165

**Comment by ProphetLamb** [comment]
According to ISO 8601 the fraction can be fixed
> Time, with optional fractional seconds and time zone (e.g., 01:45:36 or 01:45:36.123+07:00). There is no limit on the number of digits for the fractional seconds.

**Comment by ProphetLamb** [comment]
Wired that Surreal cannot handle that

**Comment by tobiemh** [comment]
@ProphetLamb the parsing isn't done with `chrono`, albeit we do use `chrono` for datetimes.

**Comment by ProphetLamb** [comment]
Fixed with #26
