### ISSUE TITLE
Bug: Fix invalid testcases

### ISSUE THREAD

**Issue by ProphetLamb** [ProphetLamb/Surreal.Net#3]
Currently, the testcases, a sequence of commands to the surrealdb server are invalid. Tho I tested all the functionality manually I can't prove that it works, we need testcases to ensure that future changes don't break existing functionality etc.

**Comment by StephenGilboy** [comment]
#5 This will get the RpcClientTests green. Hopefully I'll be able to find some more time soon to continue debugging the other tests.

**Comment by StephenGilboy** [comment]
I was able to get the Rpc DatabaseTests to pass. 

#9

**Comment by ProphetLamb** [comment]
@StephenGilboy Thanks a lot for the pr. I opened #10 with my suspicion about the cause of `JsonPropertyName` being ignored. Will fix that TMRW when setting up a cicd pipeline

**Comment by StephenGilboy** [comment]
Happy to help out! I also submitted a PR on SurrealDb to update that error message. It was a great learning opportunity though stepping through the rust code to figure out what was going on.

**Comment by ProphetLamb** [comment]
Fixed with #9 and #11
