### ISSUE TITLE
Request: Split the classes out into individual files, then into seperate projects

### ISSUE THREAD

**Issue by Du-z** [ProphetLamb/Surreal.Net#31]
Finding my way though the code base is getting tricky, Classes should be moved into their own files (The original name of the file they where in could become their folder).

When that is done, the project could be split into multiple projects maintain separation of concerns.
`Surreal.Net.Core`
`Surreal.Net.RestClient`
`Surreal.Net.RpcClient`

@ProphetLamb if you like this idea, could you execute it? I'll hold of making any changes for now, otherwise it will be a merge conflict blood bath.

**Comment by ProphetLamb** [comment]
Done :) If you have any suggestion for the current layout, please comment

**Comment by Du-z** [comment]
Yeah, looks great. is the `Directory.Build` client still required?

**Comment by ProphetLamb** [comment]
The `Directory.Build.props` file defines properties, in order to minimze the size of individual `*.csproj` files. They are required
