### ISSUE TITLE
Feature: API Documentation and Examples

### ISSUE THREAD

**Issue by ProphetLamb** [ProphetLamb/Surreal.Net#8]
Yea that stuff no one wants to do. Some "Quick Start" examples are usually better than docs. But docs would be good aswell, maybe autogenerate markdown docs and then a static website from thereon?

**Comment by AntoniosBarotsis** [comment]
I guess I'll continue the conversation here. I was looking into [XmlDocMarkdown](https://ejball.com/XmlDocMarkdown/) which seems to be working fine except for the `Extensions.Service` and `Json` assemblies where I get 

```txt
Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

Could not load file or assembly 'Rustic.Common, Version=0.5.80.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

respectively.

I've run clean builds a few times as well as added the dependencies manually (even though they are implicitly downloaded) but no progress so far. Have you come across this issue before by any chance?

**Comment by ProphetLamb** [comment]
There is no problem with the build. XmlDocMarkdown attempty to load a dll from the build directory. If you `dotnet publish` all referenced dlls should be included in the build directory. The tool doesnt seem to test the GAC or the nuget cache for assemblies

**Comment by ProphetLamb** [comment]
This can also be solved by specifying the target framework: `dotnet publish -f:net60`

**Comment by AntoniosBarotsis** [comment]
I'm also wondering if you would mind using [MkDocs Material](https://squidfunk.github.io/mkdocs-material/) instead of MdBook as MdBook needs you to explicitly specify all md files you want included unlike MkDocs which includes all files in the directory.

There are currently a little over 350 files so including them all in one file wouldn't look great.
